### ISSUE TITLE
Cannot resolve date-fns

### ISSUE THREAD

**Issue by Muscardinus94** [h6s-dev/h6s#218]
## Description
- version: ^1.0.5
- Package date-fns resolve problem

## Current
![스크린샷 2022-11-14 오후 2 43 14](https://user-images.githubusercontent.com/68500237/201585183-9123772a-b054-4127-bbc6-f72bc2072c10.png)
## Expected
Tried 
`yarn add @types/date-fns --dev`
and **resolved**
## References
https://stackoverflow.com/questions/40630893/cannot-find-module-date-fns

**Comment by SoYoung210** [comment]
@Muscardinus94

I am unable to reproduce this [on my side](https://codesandbox.io/s/solitary-sunset-u8v5ud?file=/src/App.tsx), can you make reproducible example ?

**Comment by Muscardinus94** [comment]
Node Version: v16.14.2    
react: "^18.2.0"
typescript: "^4.8.4"
@types/react: "^18.0.21",

I'll try make one!

**Comment by SoYoung210** [comment]
@Muscardinus94 If it is difficult to reproduce in Codesandbox, can you share a possible repository? Thx 🙏

**Comment by cockyb** [comment]
I also had the same problem.

https://codesandbox.io/s/elated-lovelace-mrzfck?file=/src/App.tsx

Shouldn't the date-fns package be moved from dev-dependencies to dependenciese?

**Comment by SoYoung210** [comment]
@Muscardinus94 @cockyb oh, i see... `date-fns`is peerDependency of `@h6s/calendar`.
I think it's because of tree shaking, but if it really has to be a peer dependency, I'll update the documentation. cc @JaeYeopHan 

Installing `date-fns` should fix this, and is currently intended behavior. 

thanks!
