### ISSUE TITLE
Add `isCurrentWeek` to weeks matrix

### ISSUE THREAD

**Issue by JaeYeopHan** [h6s-dev/h6s#27]

**Comment by bugtype** [comment]
`https://date-fns.org/v1.29.0/docs/isThisWeek` Is it the same?

**Comment by JaeYeopHan** [comment]
> Is the expected result the same as this? [isThisWeek](https://date-fns.org/v2.21.3/docs/isThisWeek)

yeah, maybe but "base date" is **not today**, but `cursorDate`
